package com.ifonly.museagent.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * Device Response DTO
 *
 * <p>Response payload from Echo Server after device registration or queries.
 *
 * @author if-only
 * @version 0.1.0
 */
@Data
public class DeviceResponse {

  /** Device ID (generated by server) */
  @JsonProperty("id")
  private Long id;

  /** Device unique identifier */
  @JsonProperty("deviceIdentifier")
  private String deviceIdentifier;

  /** Device name */
  @JsonProperty("deviceName")
  private String deviceName;

  /** Device type (MOBILE, DESKTOP, TABLET, AGENT) */
  @JsonProperty("deviceType")
  private String deviceType;

  /** Operating system information */
  @JsonProperty("osInfo")
  private String osInfo;

  /** Application version */
  @JsonProperty("appVersion")
  private String appVersion;

  /** Whether device is enabled */
  @JsonProperty("enabled")
  private Boolean enabled;

  /** Last seen timestamp */
  @JsonProperty("lastSeenAt")
  private LocalDateTime lastSeenAt;

  /** Created timestamp */
  @JsonProperty("createdAt")
  private LocalDateTime createdAt;

  /** Updated timestamp */
  @JsonProperty("updatedAt")
  private LocalDateTime updatedAt;
}
